version: "2"

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    govet:
      disable:
        - shadow
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters: ["gosec"]
        id: "G703"
        path: .*\.go
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
